# Generated by Django 5.2.9 on 2026-01-17 05:37

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightSidebarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('maps_url', models.URLField(blank=True)),
                ('cta_url', models.CharField(blank=True, max_length=200)),
                ('show_social', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RightSidebarPanelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('intro', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=120)),
                ('extra_html', models.TextField(blank=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.rightsidebarpanel')),
            ],
            options={
                'verbose_name': 'right sidebar panel Translation',
                'db_table': 'core_rightsidebarpanel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
