# Generated by Django 5.2.9 on 2026-01-17 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rightsidebarpanel_rightsidebarpaneltranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightsidebarpanel',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_sidebar_panels', to='core.page'),
        ),
        migrations.AddConstraint(
            model_name='rightsidebarpanel',
            constraint=models.UniqueConstraint(condition=models.Q(('page__isnull', False)), fields=('page',), name='unique_right_sidebar_panel_per_page'),
        ),
    ]
