# Generated by Django 5.2.9 on 2026-01-17 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0001_initial'),
        ('core', '0006_plan_planfeature_plantranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_interval',
            field=models.CharField(default='month', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Paste Stripe IDs here when activating payments', max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Paste Stripe IDs here when activating payments', max_length=120),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True, help_text='Printful API integration and uploads will be added in a later phase.'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past due')], default='inactive', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.plan')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='controlpanel.managedsite')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
