# Generated by Django 5.2.9 on 2026-01-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetranslation',
            name='menu_subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
