# Generated by Django 5.2.9 on 2026-01-20 15:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_page_site_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitetemplate',
            name='languages',
            field=models.JSONField(default=core.models.default_template_languages),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='sections',
            field=models.JSONField(default=core.models.default_template_sections),
        ),
    ]
