# Generated by Django 5.2.9 on 2026-01-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_site_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='subdomain',
            field=models.SlugField(blank=True, help_text="Subdomain for tenant routing (e.g., 'mim' for mim.justcodeworks.local)", max_length=63, null=True, unique=True),
        ),
    ]
