# Generated by Django 5.2.9 on 2026-01-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tenant_hero_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantherosettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
