# Generated by Django 5.2.9 on 2026-01-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_tenantherosettings_id'),
        ('core', '0030_main_site_section_settings'),
    ]

    operations = [
    ]
