# Generated by Django 5.2.9 on 2026-01-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_merge_20260125_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsitesectionsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
