# Generated by Django 5.2.11 on 2026-02-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_proformainvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='config_json_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Per-language content map, e.g. {"en": {...}, "nl": {...}, "pt": {...}}'),
        ),
    ]
