# Generated by Django 5.2.11 on 2026-03-02 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0035_sectioncontent_config_json_i18n"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email_public", models.EmailField(blank=True, max_length=254)),
                ("website_goal", models.CharField(max_length=240)),
                ("brand_color", models.CharField(blank=True, max_length=20)),
                ("profile_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
    ]
