# Generated by Django 5.2.9 on 2026-08-08 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_businessprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True)),
                ('preferred_translations', models.JSONField(blank=True, default=dict)),
                ('never_translate', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('label', models.CharField(max_length=200)),
                ('placement', models.CharField(blank=True, max_length=200)),
                ('content_type', models.CharField(default='homepage_cards_v1', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('last_source_language', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='core.site')),
            ],
            options={
                'ordering': ['site_id', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlockTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=12)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('source_language', models.CharField(blank=True, max_length=12)),
                ('source_revision_hash', models.CharField(blank=True, max_length=64)),
                ('translated_from_revision_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('current', 'Current'), ('outdated', 'Outdated'), ('needs_review', 'Needs review')], default='current', max_length=20)),
                ('is_protected', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('provenance', models.CharField(choices=[('seeded', 'Seeded'), ('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.contentblock')),
            ],
            options={
                'ordering': ['block_id', 'language_code'],
            },
        ),
        migrations.CreateModel(
            name='ContentSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_translate_updates', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_settings', to='core.site')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.UniqueConstraint(fields=('site', 'key'), name='unique_content_block_site_key'),
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_content_block_site_slug'),
        ),
        migrations.AddConstraint(
            model_name='contentblocktranslation',
            constraint=models.UniqueConstraint(fields=('block', 'language_code'), name='unique_content_block_translation_language'),
        ),
    ]
