# Generated by Django 5.2.9 on 2026-01-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('default_language', models.CharField(choices=[('nl', 'Dutch (Netherlands)'), ('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('pt-pt', 'Portuguese (Portugal)')], default='nl', max_length=10)),
                ('enabled_languages', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
