# Generated by Django 5.2.9 on 2026-01-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedsite',
            name='default_language',
            field=models.CharField(choices=[('nl', 'Dutch (Netherlands)'), ('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese')], default='nl', max_length=10),
        ),
    ]
