"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-insecure-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

MAIN_DOMAIN = os.environ.get("JCW_MAIN_DOMAIN", "justcodeworks.local")
JCW_ALLOW_IFRAME_PREVIEW = os.environ.get("JCW_ALLOW_IFRAME_PREVIEW", "").lower() in {"1", "true", "yes"}

allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
if allowed_hosts_env:
    ALLOWED_HOSTS = [
        host.strip() for host in allowed_hosts_env.split(",") if host.strip()
    ]
else:
    ALLOWED_HOSTS = [
        "127.0.0.1",
        "localhost",
        "justcodeworks.local",
        ".justcodeworks.local",
    ]

csrf_trusted_env = os.environ.get("DJANGO_CSRF_TRUSTED", "")
if csrf_trusted_env:
    CSRF_TRUSTED_ORIGINS = [
        origin.strip() for origin in csrf_trusted_env.split(",") if origin.strip()
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        "http://justcodeworks.local:8000",
        "http://mim.justcodeworks.local:8000",
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'parler',
    'core',
    'controlpanel',
]

MIDDLEWARE = [
    'core.tenant_routing.TenantRoutingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.SiteResolverMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.LaunchNoIndexMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE += [
        'core.middleware_debug.DebugRouteHeadersMiddleware',
        'core.middleware_debug.IframePreviewHeadersMiddleware',
    ]
elif JCW_ALLOW_IFRAME_PREVIEW:
    MIDDLEWARE += ['core.middleware_debug.IframePreviewHeadersMiddleware']

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'core.context_processors.seo_context',
                'core.context_processors.canonical_context',
                'core.context_processors.nav_pages',
                'core.context_processors.feature_flags',
                'core.context_processors.launch_settings',
                'core.context_processors.latest_blog_posts',
                'core.context_processors.dashboard_plan_context',
                'dashboard.context_processors.dashboard_plan_flags',
                'core.context_processors.embed_mode',
                'core.context_processors.edit_mode',
                'core.context_processors.site_mode_context',
                'core.context_processors.debug_env',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'nl'

TIME_ZONE = 'Europe/Amsterdam'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [
    ('nl', 'Nederlands'),
    ('en', 'English'),
    ('fr', 'Français'),
    ('de', 'Deutsch'),
    ('es', 'Español'),
    ('pt', 'Português'),
]


LOCALE_PATHS = [BASE_DIR / 'locale']

PARLER_LANGUAGES = {
    None: (
        {'code': 'nl'},
        {'code': 'en'},
        {'code': 'fr'},
        {'code': 'de'},
        {'code': 'es'},
        {'code': 'pt'},
    ),
    'default': {
        'fallbacks': ['en'],
        'hide_untranslated': False,
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "core:home"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Basic plan SEO indexing whitelist (slugs).
BASIC_INDEXABLE_SLUGS = ["home", "services", "contact"]

# SEO targeting limits by tier.
SEO_TIER_FOCUS_CITY_LIMITS = {
    "local": 0,
    "country": 6,
    "eu": 50,
}

SEO_TIER_ACTIVE_CITY_REQUIRED = {
    "local": True,
    "country": False,
    "eu": False,
}

SEO_ACTIVE_CITY_COOLDOWN_DAYS = 30
