"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_flag(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    os.environ.get("DJANGO_SECRET_KEY", "").strip()
    or "temporary-local-dev-key-change-me"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_flag("DJANGO_DEBUG", True)

# Launch toggle: keep site live but hidden from search engines.
# Set to False when ready for indexing.
SEO_NOINDEX = env_flag("SEO_NOINDEX", DEBUG)
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "").strip()
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "").strip()
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "").strip()
PROFORMA_FROM_EMAIL = os.environ.get("PROFORMA_FROM_EMAIL", "no-reply@justcodeworks.eu").strip()

MAIN_DOMAIN = os.environ.get("JCW_MAIN_DOMAIN", "justcodeworks.local")
JCW_ALLOW_IFRAME_PREVIEW = env_flag("JCW_ALLOW_IFRAME_PREVIEW", False)

allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
if allowed_hosts_env:
    ALLOWED_HOSTS = [
        host.strip() for host in allowed_hosts_env.split(",") if host.strip()
    ]
else:
    ALLOWED_HOSTS = [
        "127.0.0.1",
        "localhost",
        "justcodeworks.local",
        ".justcodeworks.local",
        "justcodeworks.eu",
        ".justcodeworks.eu",
    ]

csrf_trusted_env = os.environ.get("DJANGO_CSRF_TRUSTED", "")
if csrf_trusted_env:
    CSRF_TRUSTED_ORIGINS = [
        origin.strip() for origin in csrf_trusted_env.split(",") if origin.strip()
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        "http://127.0.0.1:8000",
        "http://localhost:8000",
        "http://justcodeworks.local:8000",
        "http://hmd.justcodeworks.local:8000",
        "http://autofixgarage.justcodeworks.local:8000",
        "https://justcodeworks.eu",
        "https://www.justcodeworks.eu",
]

SECURE_SSL_REDIRECT = env_flag("DJANGO_SECURE_SSL_REDIRECT", False)
SESSION_COOKIE_SECURE = env_flag("DJANGO_SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SECURE = env_flag("DJANGO_CSRF_COOKIE_SECURE", False)
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0" if DEBUG else "31536000"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_flag(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG
)
SECURE_HSTS_PRELOAD = env_flag("DJANGO_SECURE_HSTS_PRELOAD", not DEBUG)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'parler',
    'core',
    'controlpanel',
]

MIDDLEWARE = [
    'core.tenant_routing.TenantRoutingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.SiteResolverMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.LaunchNoIndexMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE += [
        'core.middleware_debug.DebugRouteHeadersMiddleware',
        'core.middleware_debug.IframePreviewHeadersMiddleware',
    ]
elif JCW_ALLOW_IFRAME_PREVIEW:
    MIDDLEWARE += ['core.middleware_debug.IframePreviewHeadersMiddleware']

ROOT_URLCONF = 'config.urls'

ADMIN_TEMPLATES_DIR = os.environ.get("ADMIN_TEMPLATES_DIR", "").strip()
DISABLE_ADMIN_TEMPLATES_OVERRIDE = (
    os.environ.get("DISABLE_ADMIN_TEMPLATES_OVERRIDE", "false").lower() in {"1", "true", "yes"}
)

template_dirs = [BASE_DIR / "templates"]
# NOTE: ADMIN_TEMPLATES_DIR takes priority and can shadow files from BASE_DIR/templates.
if ADMIN_TEMPLATES_DIR and not DISABLE_ADMIN_TEMPLATES_OVERRIDE:
    template_dirs.insert(0, Path(ADMIN_TEMPLATES_DIR))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': template_dirs,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'core.context_processors.seo_context',
                'core.context_processors.canonical_context',
                'core.context_processors.nav_pages',
                'core.context_processors.feature_flags',
                'core.context_processors.launch_settings',
                'core.context_processors.latest_blog_posts',
                'core.context_processors.dashboard_plan_context',
                'dashboard.context_processors.dashboard_plan_flags',
                'core.context_processors.embed_mode',
                'core.context_processors.edit_mode',
                'core.context_processors.site_mode_context',
                'core.context_processors.debug_env',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Europe/Amsterdam'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [
    ('nl', 'Nederlands'),
    ('en', 'English'),
    ('fr', 'Français'),
    ('de', 'Deutsch'),
    ('es', 'Español'),
    ('pt', 'Português'),
]


LOCALE_PATHS = [BASE_DIR / 'locale']

PARLER_LANGUAGES = {
    None: (
        {'code': 'nl'},
        {'code': 'en'},
        {'code': 'fr'},
        {'code': 'de'},
        {'code': 'es'},
        {'code': 'pt'},
    ),
    'default': {
        'fallbacks': ['en'],
        'hide_untranslated': False,
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / 'static']

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/accounts/post-login/"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Basic plan SEO indexing whitelist (slugs).
BASIC_INDEXABLE_SLUGS = ["home", "services", "contact"]

# SEO targeting limits by tier.
SEO_TIER_FOCUS_CITY_LIMITS = {
    "local": 0,
    "country": 6,
    "eu": 50,
}

SEO_TIER_ACTIVE_CITY_REQUIRED = {
    "local": True,
    "country": False,
    "eu": False,
}

SEO_ACTIVE_CITY_COOLDOWN_DAYS = 30
